=== nautls/ergo-meta/metadata/tokens/token-metadata.schema.json
{
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "const": "./token-metadata.schema.json"
    },
    "name": {
      "type": "string",
      "minLength": 1,
      "maxLength": 50
    },
    "description": {
      "type": "string",
      "maxLength": 500
    },
    "url": {
      "type": "string",
      "maxLength": 250
    },
    "tokenId": {
      "type": "string",
      "minLength": 64,
      "maxLength": 64
    },
    "decimals": {
      "type": "integer",
      "minimum": 0,
      "maximum": 19
    },
    "ticker": {
      "type": "string",
      "minLength": 2,
      "maxLength": 9
    },
    "logo": {
      "type": "string",
      "maxLength": 87400
    }
  },
  "required": [
    "name",
    "tokenId",
    "decimals"
  ],
  "additionalProperties": false,
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== nautls/ergo-meta/metadata/tokens/36aba4b4a97b65be491cf9f5ca57b5408b0da8d0194f30ec8330d1e8946161c1.json
{
  "$schema": "./token-metadata.schema.json",
  "tokenId": "36aba4b4a97b65be491cf9f5ca57b5408b0da8d0194f30ec8330d1e8946161c1",
  "name": "Erdoge",
  "decimals": 0,
  "description": "Like Doge but Erg.",
  "logo": "data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxzdmcKICAgd2lkdGg9IjI1IgogICBoZWlnaHQ9IjI0IgogICB2aWV3Qm94PSIwIDAgMjUgMjQiCiAgIGZpbGw9Im5vbmUiCiAgIHZlcnNpb249IjEuMSIKICAgaWQ9InN2Zzg5IgogICBzb2RpcG9kaTpkb2NuYW1lPSJlcmRvZ2Uuc3ZnIgogICBpbmtzY2FwZTp2ZXJzaW9uPSIxLjEuMSAoYzMwODRlZiwgMjAyMS0wOS0yMikiCiAgIHhtbG5zOmlua3NjYXBlPSJodHRwOi8vd3d3Lmlua3NjYXBlLm9yZy9uYW1lc3BhY2VzL2lua3NjYXBlIgogICB4bWxuczpzb2RpcG9kaT0iaHR0cDovL3NvZGlwb2RpLnNvdXJjZWZvcmdlLm5ldC9EVEQvc29kaXBvZGktMC5kdGQiCiAgIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICAgeG1sbnM6c3ZnPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgPGRlZnMKICAgICBpZD0iZGVmczkzIiAvPgogIDxzb2RpcG9kaTpuYW1lZHZpZXcKICAgICBpZD0ibmFtZWR2aWV3OTEiCiAgICAgcGFnZWNvbG9yPSIjZmZmZmZmIgogICAgIGJvcmRlcmNvbG9yPSIjNjY2NjY2IgogICAgIGJvcmRlcm9wYWNpdHk9IjEuMCIKICAgICBpbmtzY2FwZTpwYWdlc2hhZG93PSIyIgogICAgIGlua3NjYXBlOnBhZ2VvcGFjaXR5PSIwLjAiCiAgICAgaW5rc2NhcGU6cGFnZWNoZWNrZXJib2FyZD0iMCIKICAgICBzaG93Z3JpZD0iZmFsc2UiCiAgICAgaW5rc2NhcGU6em9vbT0iMTEuMzMzMzMzIgogICAgIGlua3NjYXBlOmN4PSItMC45NzA1ODgyNiIKICAgICBpbmtzY2FwZTpjeT0iMTEuMjk0MTE4IgogICAgIGlua3NjYXBlOndpbmRvdy13aWR0aD0iMTQxNyIKICAgICBpbmtzY2FwZTp3aW5kb3ctaGVpZ2h0PSI3NjYiCiAgICAgaW5rc2NhcGU6d2luZG93LXg9IjAiCiAgICAgaW5rc2NhcGU6d2luZG93LXk9IjI1IgogICAgIGlua3NjYXBlOndpbmRvdy1tYXhpbWl6ZWQ9IjAiCiAgICAgaW5rc2NhcGU6Y3VycmVudC1sYXllcj0ic3ZnODkiIC8+CiAgPGcKICAgICBpZD0iZzI1NiIKICAgICB0cmFuc2Zvcm09Im1hdHJpeCgwLjkxNTQ3NTIsMCwwLDAuOTE1NDc1MiwxLjUwNjQ3MDMsMS4wMTQyOTc2KSI+CiAgICA8cGF0aAogICAgICAgZD0ibSAwLjYzODY3MywxMS45OTg5IGMgMCwwLjExNTggMC4wMjM3NjUsMC4yMzE3IDAuMDY4MzIzLDAuMzQxNiBMIDMuNzc1NiwxOS43NTIxIGMgMC4wODkxMiwwLjIxNjggMC4yNjQzOCwwLjM5MjEgMC40ODEyMywwLjQ4MTIgbCA3LjQxMTU3LDMuMDY4NiBjIDAuMjE2OSwwLjA4OTEgMC40NjM0LDAuMDg5MSAwLjY4MDMsMCBsIDcuNDE0NSwtMy4wNjg2IGMgMC4yMTY5LC0wLjA4OTEgMC4zOTIxLC0wLjI2NDQgMC40ODEzLC0wLjQ4MTIgbCAzLjA3MTUsLTcuNDExNiBjIDAuMDQ0NiwtMC4xMDk5IDAuMDY4MywtMC4yMjU4IDAuMDY4MywtMC4zNDE2IDAsLTAuMTE1OSAtMC4wMjM3LC0wLjIzMTcgLTAuMDY4MywtMC4zNDE2IEwgMjAuMjQ0NSw0LjI0NTY5IEMgMjAuMTU1Myw0LjAyODg0IDE5Ljk4MDEsMy44NTM1NyAxOS43NjMyLDMuNzY0NDYgTCAxMi4zNTE2LDAuNjkyODgzIGMgLTAuMjE2OCwtMC4wODkxMTcgLTAuNDYzNCwtMC4wODkxMTcgLTAuNjgwMiwwIEwgNC4yNTY4MywzLjc2NDQ2IEMgNC4wMzk5OCwzLjg1MzU3IDMuODY0NzIsNC4wMjg4NCAzLjc3NTYsNC4yNDU2OSBMIDAuNzA0MDI2LDExLjY1NzMgQyAwLjY1OTQ2NywxMS43NjcyIDAuNjM4NjczLDExLjg4MyAwLjYzODY3MywxMS45OTg5IFoiCiAgICAgICBmaWxsPSIjNTkwMGZmIgogICAgICAgaWQ9InBhdGg5IiAvPgogICAgPHBhdGgKICAgICAgIGQ9Ik0gNC4wMjgxLDE0LjQxOTkgQyAzLjk5MjQ1LDEzLjE3ODIgMy41NTU3OCwxMC44MDE3IDMuNzEwMjUsMTAuMjY3IDMuODY0NzIsOS43MzIzNCA0LjcxNDMsNy45NTg5MSA0LjcxNDMsNy45NTg5MSBjIDAsMCAtMS42OTYyLC01LjIxNjMzIC0wLjAzNTY1LC03LjE2Nzk5NiAxLjA1NDU2LC0xLjIzNTc1OCAzLjAwNjIyLDIuMjYzNTc2IDQuMTExMjgsMy41ODI1MDYgMCwwIDEuODg2MjcsLTAuMzY1MzggMy42MTgxNywtMC4zMjk3MyAxLjczMTgsMC4wMzU2NSAzLjY2NTcsMC45MjM4NSAzLjY2NTcsMC45MjM4NSAwLDAgMi45MDIyLC00LjM1MTg5IDQuMTMyLC0zLjU1ODc1IDEuNjI0OSwxLjA0NTY0IDAuOTAzMSw1LjY5NzU2IC0wLjA1NjQsNy41MzkzMiAwLDEuMzQ1NjkgMC40OTAxLDIuOTI1OTkgLTAuNjY1NCw0LjkxNjI5IC0xLjE1NTYsMS45ODczIC0zLjEwNDMsNC41NjU4IC0zLjEwNDMsNC41NjU4IDAsMCAtOC4xMDA3MSwwLjUyNTggLTguMjU4MTUsMC40NTQ1IEMgNy45NjQxMSwxOC44MTM0IDQuMDI4MSwxNC40MTk5IDQuMDI4MSwxNC40MTk5IFoiCiAgICAgICBmaWxsPSIjZmZhMTAwIgogICAgICAgaWQ9InBhdGgxMSIgLz4KICAgIDxwYXRoCiAgICAgICBkPSJNIDE5Ljc5NTksOS4xMzgyMiBDIDIwLjQ5MSwxMS42NDg0IDE4LjgyNzUsMTMuMyAxNi42Nzk4LDEzLjMgYyAtMi4xNDQ4LDAgLTIuMTc0NSwtMy4zNDc4NCAtNC43MjMyLC0zLjM1Njc1IC0wLjAwMywwIC0wLjAwMywwIC0wLjAwNiwwIC0wLjAwMywwIC0wLjAwMywwIC0wLjAwNTksMCBDIDkuMzk1OTIsOS45NTUxMyA5LjM2OTE5LDEzLjMgNy4yMjE0NiwxMy4zIDUuMDczNzQsMTMuMyAzLjQxMDIyLDExLjY0ODQgNC4xMDUzMyw5LjEzODIyIGMgMCwwIC0wLjgxOTg4LDEuNjYwNTggLTAuNzc1MzIsNC4xNjE3OCAwLjA0MTU5LDIuNDk4MiAxLjI4OTIzLDcuMDkzNyAxLjI4OTIzLDcuMDkzNyBsIDcuMzI1NDYsMi41MzY5IHYgMC4wMDMgbCAwLjAwNTksLTAuMDAzIDAuMDA2LDAuMDAzIHYgLTAuMDAzIGwgNy44MDY2LC0yLjY5NzMgYyAwLDAgMC43NjY0LC00LjQzMjEgMC44MTEsLTYuOTMzMyAwLjA0MTYsLTIuNDk4MyAtMC43NzgzLC00LjE2MTc4IC0wLjc3ODMsLTQuMTYxNzggeiIKICAgICAgIGZpbGw9IiNmZmZmZmYiCiAgICAgICBpZD0icGF0aDEzIiAvPgogICAgPHBhdGgKICAgICAgIGQ9Ik0gNC4yNTY4MywyMC41NjYgQyA0LjExMTI3LDIwLjU2NiAzLjk3NDYyLDIwLjQ2OCAzLjkzNjAxLDIwLjMxOTUgMS43NDA3NSwxMi4xNDE1IDMuNzYzNzEsOC45NDUxNCA0Ljk3NTcxLDcuMDM1MDYgTCA1LjA0Nyw2LjkyMjE4IGMgMC4wOTgwMywtMC4xNTQ0NyAwLjMwMywtMC4yMDIgMC40NjA0NCwtMC4xMDM5NyAwLjE1NDQ3LDAuMDk4MDMgMC4yMDIsMC4zMDMgMC4xMDM5NywwLjQ2MDQ0IEwgNS41NDAxMiw3LjM5MTUzIEMgNC45MzcwOSw4LjM0MjExIDQuMTg4NTEsOS41MjQ0IDMuODMyMDQsMTEuNDc2MSBjIC0wLjE5NjA2LDEuMDY5NCAtMC4yNDk1MywyLjI3MjUgLTAuMTYwNDEsMy41NzM2IDAuMTA2OTQsMS41MjM5IDAuNDEyOTEsMy4yMzc5IDAuOTExOTYsNS4wOTc1IDAuMDQ3NTMsMC4xNzgyIC0wLjA1NjQ0LDAuMzU5NCAtMC4yMzQ2NywwLjQwNjkgLTAuMDM1NjUsMC4wMDkgLTAuMDYyMzksMC4wMTE5IC0wLjA5MjA5LDAuMDExOSB6IgogICAgICAgZmlsbD0iIzI0MWYyMCIKICAgICAgIGlkPSJwYXRoMTUiIC8+CiAgICA8cGF0aAogICAgICAgZD0iTSA2LjQ0OTExLDEwLjQyMTUgQyA2LjQ0NjE0LDEwLjM1MDIgNi40NDMxNywxMC4yNzg5IDYuNDQzMTcsMTAuMjA0NyA2LjQ0MzE3LDkuMjk1NjcgNi43MTk0NCw4LjU0NDExIDcuNTk4NzMsOC40MjgyNiA3LjUyMTQ5LDguNDE5MzUgNy40NDEyOCw4LjQxMzQxIDcuMzYxMDgsOC40MTM0MSBjIC0wLjk4OTIsMCAtMS43OTEyNiwwLjgwMjA1IC0xLjc5MTI2LDEuNzkxMjkgMCwwLjI2NzMgMC4wNTk0MSwwLjUyMjggMC4xNjYzNiwwLjc1MTUgMC4xNzIyOSwtMC4yMjU3IDAuNDE4ODUsLTAuNDEyOSAwLjcxMjkzLC0wLjUzNDcgeiIKICAgICAgIGZpbGw9IiNhNTY2MGMiCiAgICAgICBpZD0icGF0aDE3IiAvPgogICAgPHBhdGgKICAgICAgIGQ9Im0gMTUuOTQwMSwxMC40MjE1IGMgLTAuMDAzLC0wLjA3MTMgLTAuMDA1OSwtMC4xNDI2IC0wLjAwNTksLTAuMjE2OCAwLC0wLjkwOTAzIDAuMjc2MiwtMS42NjA1OSAxLjE1NTUsLTEuNzc2NDQgLTAuMDc3MiwtMC4wMDg5MSAtMC4xNTc0LC0wLjAxNDg1IC0wLjIzNzYsLTAuMDE0ODUgLTAuOTg5MiwwIC0xLjc5MTMsMC44MDIwNSAtMS43OTEzLDEuNzkxMjkgMCwwLjI2NzMgMC4wNTk0LDAuNTIyOCAwLjE2NjQsMC43NTE1IDAuMTY5MywtMC4yMjU3IDAuNDE4OCwtMC40MTI5IDAuNzEyOSwtMC41MzQ3IHoiCiAgICAgICBmaWxsPSIjYTU2NjBjIgogICAgICAgaWQ9InBhdGgxOSIgLz4KICAgIDxwYXRoCiAgICAgICBkPSJtIDcuMjk4NywxMS45OTg5IGMgMC44MjE5NCwwIDEuNDg4MjUsLTAuMzg4NCAxLjQ4ODI1LC0wLjg2NzQgMCwtMC40NzkxIC0wLjY2NjMxLC0wLjg2NzQgLTEuNDg4MjUsLTAuODY3NCAtMC44MjE5NCwwIC0xLjQ4ODI2LDAuMzg4MyAtMS40ODgyNiwwLjg2NzQgMCwwLjQ3OSAwLjY2NjMyLDAuODY3NCAxLjQ4ODI2LDAuODY3NCB6IgogICAgICAgZmlsbD0iI2ZmZmZmZiIKICAgICAgIGlkPSJwYXRoMjEiIC8+CiAgICA8cGF0aAogICAgICAgZD0ibSAxNi43NiwxMS45OTg5IGMgMC44MjE5LDAgMS40ODgyLC0wLjM4ODQgMS40ODgyLC0wLjg2NzQgMCwtMC40NzkxIC0wLjY2NjMsLTAuODY3NCAtMS40ODgyLC0wLjg2NzQgLTAuODIyLDAgLTEuNDg4MywwLjM4ODMgLTEuNDg4MywwLjg2NzQgMCwwLjQ3OSAwLjY2NjMsMC44Njc0IDEuNDg4MywwLjg2NzQgeiIKICAgICAgIGZpbGw9IiNmZmZmZmYiCiAgICAgICBpZD0icGF0aDIzIiAvPgogICAgPHBhdGgKICAgICAgIGQ9Im0gMTMuNjI5LDE0LjQ3OTMgYyAwLjgyNTgsMC44MjU4IDEuNDkxMiw0LjQ3MzcgLTEuMzU3Niw0LjQ3MzcgLTIuODQ4NzQsMCAtMi40NzE0OCwtMy42NDc5IC0xLjY0NTcsLTQuNDczNyBsIDEuNTU5NiwtMC40MDk5IHoiCiAgICAgICBmaWxsPSIjZmY1NTM3IgogICAgICAgaWQ9InBhdGgyNSIgLz4KICAgIDxwYXRoCiAgICAgICBkPSJtIDcuMzYxMDgsMTIuMjYwMyBjIC0xLjEzMTc5LDAgLTIuMDUyNjcsLTAuOTIwOSAtMi4wNTI2NywtMi4wNTI3IDAsLTEuMTMxNzUgMC45MjA4OCwtMi4wNTI2MyAyLjA1MjY3LC0yLjA1MjYzIDEuMTMxNzksMCAyLjA1MjY2LDAuOTIwODggMi4wNTI2NiwyLjA1MjYzIDAsMS4xMzE4IC0wLjkyMDg3LDIuMDUyNyAtMi4wNTI2NiwyLjA1MjcgeiBtIDAsLTMuNTgyNTEgYyAtMC44NDM2NCwwIC0xLjUyOTg1LDAuNjg2MiAtMS41Mjk4NSwxLjUyOTgxIDAsMC44NDM3IDAuNjg2MjEsMS41Mjk5IDEuNTI5ODUsMS41Mjk5IDAuODQzNjQsMCAxLjUyOTg0LC0wLjY4NjIgMS41Mjk4NCwtMS41Mjk5IDAsLTAuODQzNjEgLTAuNjg2MiwtMS41Mjk4MSAtMS41Mjk4NCwtMS41Mjk4MSB6IgogICAgICAgZmlsbD0iIzI0MWYyMCIKICAgICAgIGlkPSJwYXRoMjciIC8+CiAgICA8cGF0aAogICAgICAgZD0ibSA4LjkxNzYsMTEuMzAzOCBjIC0wLjE0NTU2LDAgLTAuMjYxNDEsLTAuMTE1OSAtMC4yNjE0MSwtMC4yNjE0IDAsLTAuMDk4MSAtMC4xMTg4MiwtMC4yMTk5IC0wLjMwODk0LC0wLjMxNDkgLTAuMjU1NDcsLTAuMTI3OCAtMC42MTE5NCwtMC4xOTkgLTAuOTgzMjYsLTAuMTk5IC0wLjM3MTMyLDAgLTAuNzI3NzksMC4wNzQyIC0wLjk4MzI2LDAuMTk5IC0wLjE5MDEyLDAuMDk1IC0wLjMwODk0LDAuMjE2OCAtMC4zMDg5NCwwLjMxNDkgMCwwLjE0NTUgLTAuMTE1ODUsMC4yNjE0IC0wLjI2MTQxLDAuMjYxNCAtMC4xNDU1NiwwIC0wLjI2MTQxLC0wLjExNTkgLTAuMjYxNDEsLTAuMjYxNCAwLC0wLjU5MTIgMC43ODEyNiwtMS4wMzY4IDEuODE1MDIsLTEuMDM2OCAxLjAzMzc2LDAgMS44MTUwMiwwLjQ0NTYgMS44MTUwMiwxLjAzNjggMCwwLjE0NTUgLTAuMTE1ODUsMC4yNjE0IC0wLjI2MTQxLDAuMjYxNCB6IgogICAgICAgZmlsbD0iIzI0MWYyMCIKICAgICAgIGlkPSJwYXRoMjkiIC8+CiAgICA8cGF0aAogICAgICAgZD0ibSA3LjM2MTAyLDEwLjIwNzYgYyAtMC4yNzAzMiwwIC0wLjUyNTc5LDAuMDM4NyAtMC43NTc1LDAuMTA0IDAuMDI5NzEsMC42Njg0IDAuMzU2NDcsMS4xOTcxIDAuNzU3NSwxLjE5NzEgMC40MDEwMiwwIDAuNzI3NzksLTAuNTI1NyAwLjc1NzQ5LC0xLjE5NzEgLTAuMjMxNywtMC4wNjgzIC0wLjQ4NzE3LC0wLjEwNCAtMC43NTc0OSwtMC4xMDQgeiIKICAgICAgIGZpbGw9IiMyNDFmMjAiCiAgICAgICBpZD0icGF0aDMxIiAvPgogICAgPHBhdGgKICAgICAgIGQ9Im0gMTYuNzU5OSwxMi4yNjAzIGMgLTEuMTMxOCwwIC0yLjA1MjcsLTAuOTIwOSAtMi4wNTI3LC0yLjA1MjcgMCwtMS4xMzE3NSAwLjkyMDksLTIuMDUyNjMgMi4wNTI3LC0yLjA1MjYzIDEuMTMxOCwwIDIuMDUyNywwLjkyMDg4IDIuMDUyNywyLjA1MjYzIDAsMS4xMzE4IC0wLjkyMDksMi4wNTI3IC0yLjA1MjcsMi4wNTI3IHogbSAwLC0zLjU4MjUxIGMgLTAuODQzNiwwIC0xLjUyOTgsMC42ODYyIC0xLjUyOTgsMS41Mjk4MSAwLDAuODQzNyAwLjY4NjIsMS41Mjk5IDEuNTI5OCwxLjUyOTkgMC44NDM3LDAgMS41Mjk5LC0wLjY4NjIgMS41Mjk5LC0xLjUyOTkgMCwtMC44NDM2MSAtMC42ODYyLC0xLjUyOTgxIC0xLjUyOTksLTEuNTI5ODEgeiIKICAgICAgIGZpbGw9IiMyNDFmMjAiCiAgICAgICBpZD0icGF0aDMzIiAvPgogICAgPHBhdGgKICAgICAgIGQ9Im0gMTguMzEzNSwxMS4zMDM4IGMgLTAuMTQ1NSwwIC0wLjI2MTQsLTAuMTE1OSAtMC4yNjE0LC0wLjI2MTQgMCwtMC4wOTgxIC0wLjExODgsLTAuMjE5OSAtMC4zMDg5LC0wLjMxNDkgLTAuMjU1NSwtMC4xMjc4IC0wLjYxMTksLTAuMTk5IC0wLjk4MzMsLTAuMTk5IC0wLjM3MTMsMCAtMC43Mjc4LDAuMDc0MiAtMC45ODMyLDAuMTk5IC0wLjE5MDEsMC4wOTUgLTAuMzA5LDAuMjE2OCAtMC4zMDksMC4zMTQ5IDAsMC4xNDU1IC0wLjExNTgsMC4yNjE0IC0wLjI2MTQsMC4yNjE0IC0wLjE0NTUsMCAtMC4yNjE0LC0wLjExNTkgLTAuMjYxNCwtMC4yNjE0IDAsLTAuNTkxMiAwLjc4MTMsLTEuMDM2OCAxLjgxNSwtMS4wMzY4IDEuMDMzOCwwIDEuODE1MSwwLjQ0NTYgMS44MTUxLDEuMDM2OCAwLDAuMTQ1NSAtMC4xMTU5LDAuMjYxNCAtMC4yNjE1LDAuMjYxNCB6IgogICAgICAgZmlsbD0iIzI0MWYyMCIKICAgICAgIGlkPSJwYXRoMzUiIC8+CiAgICA8cGF0aAogICAgICAgZD0ibSAxNi43NTk5LDEwLjIwNzYgYyAtMC4yNzAzLDAgLTAuNTI1OCwwLjAzODcgLTAuNzU3NSwwLjEwNCAwLjAzMjcsMC42NzE0IDAuMzU5NSwxLjE5NzEgMC43NTc1LDEuMTk3MSAwLjQwMTEsMCAwLjcyNzgsLTAuNTI1NyAwLjc1NzUsLTEuMTk3MSAtMC4yMzE3LC0wLjA2ODMgLTAuNDg3MSwtMC4xMDQgLTAuNzU3NSwtMC4xMDQgeiIKICAgICAgIGZpbGw9IiMyNDFmMjAiCiAgICAgICBpZD0icGF0aDM3IiAvPgo
